#!/bin/sh

#
# Run xcowsay at the specified time using atd
#

# Might not have a display
if [ "$DISPLAY" = "" ]; then
    DISPLAY=:0.0
fi

# xcowsay may not be on the PATH...
# ...but it should be in the same directory as xcowat
PATH=$PATH:`dirname $0`

echo "env DISPLAY=$DISPLAY PATH=$PATH xcowsay \"$2\"" | at $1
